---
- name: Create npm user
  ansible.builtin.user:
    name: "{{ npm_container_user }}"
    shell: /sbin/nologin
    create_home: true
    state: present
  become: true

- name: Get created user metadata
  ansible.builtin.getent:
    database: passwd
    key: "{{ npm_container_user }}"

- name: Setting user id and group id facts
  ansible.builtin.set_fact:
    created_uid: "{{ ansible_facts.getent_passwd[npm_container_user].1 }}"
    created_gid: "{{ ansible_facts.getent_passwd[npm_container_user].2 }}"

- name: Ensure npm folders exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ npm_container_user }}"
    group: "{{ npm_container_user }}"
    state: directory
    mode: 0755
  loop:
    - "{{ npm_host_config_path }}"
    - "{{ npm_host_db_path }}"

- name: Copy npm docker-compose template.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ npm_host_config_path }}/docker-compose.yml"
    owner: "{{ npm_container_user }}"
    group: "{{ npm_container_user }}"
    mode: 0644
  become: true

- name: Create systemd nginx-proxy-manager service.
  ansible.builtin.template:
    src: templates/npm.service.j2
    dest: "/etc/systemd/system/npm.service"
    mode: 0644
  become: true

- name: Ensure npm.service is started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: npm
  become: true

- name: Check npm container
  ansible.builtin.uri:
    url: "http://localhost:{{ npm_ui_host_http_port }}"
    status_code: [200, 401]
  register: result
  until: result.status == 200 or result.status == 401
  retries: 5
  delay: 60

- name: Remove old image versions
  become: true
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
  notify: Restart Docker service
